### ISSUE TITLE
Recent | escape removal - not on all?

### ISSUE THREAD

**Issue by Chrisedmo** [benwatts/shopify-theme-radiance#3]
Hi - i've been referring to this project as i'm working on a theme, and I noticed that you recently removed a lot of the | escapes from the liquid filters? (commit: d3ce50f5eb6043a24989a7309d4db350eeb6c6ae ) But not all of them - Especially on the Layout.liquid file ? Is there a reason for this? 

I was just about to do a global find and replace to remove all '| escape' references - should i not do that?

**Comment by carolineschnapp** [comment]
The complete answer is a bit complex: some tags in Liquid already return escaped content, while some others don't. Escaping used to create problems on already escaped content, but not anymore last time I checked. Escaping HTML is problematic and some customers use HTML in their link titles - to, say, make a link red - of their product titles - to, say, add a br tag in it. 

Simple albeit incomplete answer: the escape filter is safe to use when the tag is used as an HTML attribute, and should not be used when the tag is HTML content.
